language: python
cache: pip
python:
  - "2.7.11"

before_install:
  - export DJANGO_SETTINGS_MODULE=kikar_hamedina.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/build/hasadna/kikar-hamedina/kikar_hamedina

install:
 - "pip install pip -U"
 - "pip install -r requirements/vps.txt"

services: postgresql

before_script:
  # Prepare DB
#  - psql -c "CREATE DATABASE travisci;" -U postgres
#  - python kikar_hamedina/manage.py migrate
#  - python kikar_hamedina/manage.py loaddata fixture data_fixture_mks.json --app mks
#  - python kikar_hamedina/manage.py loaddata fixture data_fixture_facebook_feeds.json --app facebook_feeds

script:
  - cd kikar_hamedina; python manage.py test

after_script:
  - coveralls
