sudo: false
language: python
cache: pip
python:
  - "2.7.11"

before_install:
  - export DJANGO_SETTINGS_MODULE=kikar_hamedina.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/build/hasadna/kikar-hamedina/kikar_hamedina

install:
 - "pip install pip -U"
 - "pip install -r requirements/vps.txt"
 - "pip install coveralls"

services: postgresql

addons:
  postgresql: "9.3"


before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python kikar_hamedina/manage.py migrate

script:
  - cd kikar_hamedina; coverage run  --source=. manage.py test

after_script:
  - coveralls
