sudo: false
language: python
cache: pip
python:
  - "2.7.11"

install:
 - "pip install pip -U"
 - "pip install -r requirements/vps.txt"

services: postgresql

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - cd kikar_hamedina; python manage.py test

after_script:
  - coveralls
